/*
 * 「稻浪长歌」湖南省农耕文化地图 - 数据层
 * 三色图层：赭色(古代)、翠绿(现代)、朱砂红(红色)
 */

const CDN = "https://d2xsxph8kpxj0f.cloudfront.net/310519663561381094/XvpBgf3UM3n5Xfk237Khhb";

export const IMAGES = {
  heroBanner: `${CDN}/hero_banner_099bf9fc.png`,
  ancientFarming: `${CDN}/ancient_farming_eda82c55.png`,
  modernAgriculture: `${CDN}/modern_agriculture_14989a84.png`,
  redHeritage: `${CDN}/red_heritage_59110891.png`,
  hunanMapArtistic: `${CDN}/hunan_map_artistic_65b435fd.png`,
  chengtoushan: `${CDN}/chengtoushan_d51f3a4d.jpeg`,
  ziquejie: `${CDN}/ziquejie_49f9136e.jpeg`,
  dongtingHarvest: `${CDN}/dongting_harvest_b45f9f18.jpg`,
  anjiangRice: `${CDN}/anjiang_rice_45944959.jpg`,
  yuanlongping: `${CDN}/yuanlongping_46ec287d.jpg`,
  liuyangRice: `${CDN}/liuyang_rice_0ffb7c5e.jpg`,
  nanxianShrimp: `${CDN}/nanxian_shrimp_33bb94d8.jpg`,
  shaoshan: `${CDN}/shaoshan_9efb4a45.jpg`,
  sangzhi: `${CDN}/sangzhi_df27ebe6.jpeg`,
  buffaloPlowing: `${CDN}/buffalo_plowing_7ba2522a.jpg`,
  teaGarden: `${CDN}/tea_garden_12ef4975.jpg`,
  xiangxiTerrace: `${CDN}/xiangxi_terrace_4600356f.jpg`,
  dongtingModern: `${CDN}/dongting_modern_5bd637ea.jpg`,
  traditionalTools: `${CDN}/traditional_tools_dd314894.jpg`,
  droneFarming: `${CDN}/drone_farming_7220ad7e.jpg`,
  beautifulVillage: `${CDN}/beautiful_village_748d78c7.jpg`,
  harvestFestival: `${CDN}/harvest_festival_02125575.jpg`,
  yuchanyan: `${CDN}/yuchanyan_c5c4f300.jpg`,
};

export type SiteCategory = "ancient" | "modern" | "red";

export interface FarmingSite {
  id: string;
  name: string;
  nameEn: string;
  category: SiteCategory;
  lat: number;
  lng: number;
  city: string;
  description: string;
  details: string;
  year?: string;
  image: string;
  tags: string[];
  significance: string;
}

export const CATEGORY_CONFIG = {
  ancient: {
    label: "古代农耕遗址",
    labelEn: "Ancient Farming Sites",
    color: "#8B6914",
    colorLight: "#D4A76A",
    colorBg: "rgba(139, 105, 20, 0.15)",
    icon: "🏛️",
    count: 43,
    description: "从万年前的稻作起源到千年梯田，湖湘大地孕育了中华农耕文明的根脉",
  },
  modern: {
    label: "现代农耕地标",
    labelEn: "Modern Agriculture",
    color: "#1B7A4E",
    colorLight: "#4ECDC4",
    colorBg: "rgba(27, 122, 78, 0.15)",
    icon: "🌾",
    count: 55,
    description: "从杂交水稻到智慧农业，湖南引领中国农业现代化的前沿探索",
  },
  red: {
    label: "红色农事旧址",
    labelEn: "Red Heritage Sites",
    color: "#C0392B",
    colorLight: "#E85D4A",
    colorBg: "rgba(192, 57, 43, 0.15)",
    icon: "🚩",
    count: 11,
    description: "革命火种与农耕大地交融，铸就湖湘红色农魂的不朽丰碑",
  },
};

export const SITES: FarmingSite[] = [
  // ===== 古代农耕遗址 =====
  {
    id: "yuchanyan",
    name: "玉蟾岩遗址",
    nameEn: "Yuchanyan Site",
    category: "ancient",
    lat: 25.95,
    lng: 111.55,
    city: "永州道县",
    description: "世界最早的人工栽培稻遗存发现地，距今约1.4万-1.8万年",
    details: "玉蟾岩遗址出土了世界上已知最早的人工栽培稻标本，将人类稻作农业的历史推前至距今1.4万-1.8万年前，被誉为'天下谷源'。同时出土了世界上最早的陶器残片。",
    year: "距今1.4万-1.8万年",
    image: IMAGES.yuchanyan,
    tags: ["世界遗产", "稻作起源", "考古发现"],
    significance: "世界稻作农业起源地",
  },
  {
    id: "chengtoushan",
    name: "城头山遗址",
    nameEn: "Chengtoushan Site",
    category: "ancient",
    lat: 29.67,
    lng: 111.52,
    city: "常德澧县",
    description: "中国最早的古城遗址，发现了世界最早的水稻田遗迹",
    details: "城头山遗址是迄今为止中国发现的年代最早、保存最完整的古城址，距今约6000年。遗址内发现了世界上已知最早的水稻田遗迹——汤家岗文化时期的古稻田，面积约200平方米。",
    year: "距今约6000年",
    image: IMAGES.chengtoushan,
    tags: ["国家考古遗址公园", "古城遗址", "水稻田"],
    significance: "中国最早的古城址与水稻田",
  },
  {
    id: "ziquejie",
    name: "紫鹊界梯田",
    nameEn: "Ziquejie Terraces",
    category: "ancient",
    lat: 27.75,
    lng: 111.05,
    city: "娄底新化",
    description: "始于秦汉的千年梯田，世界灌溉工程遗产",
    details: "紫鹊界梯田始于秦汉，盛于宋明，已有两千余年历史。梯田依山就势，层层叠叠，总面积达8万余亩。其独特的自流灌溉系统无需修建水库和水渠，完全依靠山体自身的储水功能，被誉为世界水利灌溉工程的奇迹。",
    year: "始于秦汉，2000余年",
    image: IMAGES.ziquejie,
    tags: ["世界灌溉工程遗产", "全球重要农业文化遗产", "梯田"],
    significance: "世界灌溉工程遗产",
  },
  {
    id: "pengtoushan",
    name: "彭头山遗址",
    nameEn: "Pengtoushan Site",
    category: "ancient",
    lat: 29.62,
    lng: 111.60,
    city: "常德澧县",
    description: "长江中游最早的新石器时代遗址之一，出土大量稻谷遗存",
    details: "彭头山遗址距今约9000年，是长江中游地区已知最早的新石器时代遗址之一。在遗址陶片中发现了大量稻谷壳遗存，证明当时已有较为成熟的稻作农业。",
    year: "距今约9000年",
    image: IMAGES.ancientFarming,
    tags: ["新石器时代", "稻谷遗存", "考古遗址"],
    significance: "长江中游最早新石器遗址",
  },
  {
    id: "gaomiao",
    name: "高庙遗址",
    nameEn: "Gaomiao Site",
    category: "ancient",
    lat: 27.45,
    lng: 110.10,
    city: "怀化洪江",
    description: "沅水流域史前文化的代表，出土精美白陶与祭祀遗迹",
    details: "高庙遗址距今约7800年，是沅水流域史前文化的杰出代表。遗址出土了大量精美的白陶器物，其上的凤鸟纹、獠牙兽面纹等图案被认为是中国最早的艺术杰作之一，反映了当时高度发达的农耕祭祀文化。",
    year: "距今约7800年",
    image: IMAGES.buffaloPlowing,
    tags: ["白陶文化", "祭祀遗迹", "沅水文明"],
    significance: "沅水流域史前文化代表",
  },
  {
    id: "liye",
    name: "里耶古城",
    nameEn: "Liye Ancient City",
    category: "ancient",
    lat: 28.98,
    lng: 109.47,
    city: "湘西龙山",
    description: "出土秦简3.6万枚，记录了秦代农业管理制度",
    details: "里耶古城出土的3.6万枚秦简中，包含大量关于秦代农业生产、田赋征收、粮食储运的珍贵记录，是研究秦代农业管理制度的第一手资料。",
    year: "秦代（约公元前221年）",
    image: IMAGES.xiangxiTerrace,
    tags: ["秦简", "古城遗址", "农业管理"],
    significance: "秦代农业管理制度珍贵记录",
  },
  {
    id: "mawangdui",
    name: "马王堆汉墓",
    nameEn: "Mawangdui Han Tombs",
    category: "ancient",
    lat: 28.22,
    lng: 113.02,
    city: "长沙",
    description: "出土大量农作物种子和食物标本，展现汉代湖南农业盛况",
    details: "马王堆汉墓出土了稻、麦、黍、粟等多种农作物种子，以及丰富的食物标本和农业相关帛书，生动展现了2100多年前湖南地区发达的农业生产和饮食文化。",
    year: "西汉（约公元前168年）",
    image: IMAGES.traditionalTools,
    tags: ["汉墓", "农作物标本", "帛书"],
    significance: "汉代湖南农业文明的实物见证",
  },

  // ===== 现代农耕地标 =====
  {
    id: "anjiang",
    name: "安江农校纪念园",
    nameEn: "Anjiang Agricultural School",
    category: "modern",
    lat: 27.37,
    lng: 110.18,
    city: "怀化洪江",
    description: "袁隆平杂交水稻研究起步之地，中国杂交水稻的摇篮",
    details: "安江农校是袁隆平院士工作37年的地方，也是杂交水稻研究的起步之地。1964年，袁隆平在这里发现了第一株天然雄性不育株，开启了杂交水稻研究的伟大征程。现已建成安江农校纪念园，是全国重点文物保护单位。",
    year: "1964年",
    image: IMAGES.anjiangRice,
    tags: ["杂交水稻", "袁隆平", "全国重点文保"],
    significance: "杂交水稻研究发源地",
  },
  {
    id: "longping_museum",
    name: "隆平水稻博物馆",
    nameEn: "Longping Rice Museum",
    category: "modern",
    lat: 28.13,
    lng: 113.08,
    city: "长沙",
    description: "世界首个大型水稻博物馆，全面展示水稻文明",
    details: "隆平水稻博物馆是世界上第一个以水稻为主题的大型博物馆，总建筑面积约1.8万平方米。馆内设有稻米香万年、奇异的旅程、梦想成真三大常设展厅，全面展示了水稻的起源、传播和杂交水稻的伟大成就。",
    year: "2019年开馆",
    image: IMAGES.yuanlongping,
    tags: ["水稻博物馆", "科普教育", "文化地标"],
    significance: "世界首个水稻主题博物馆",
  },
  {
    id: "nanxian_shrimp",
    name: "南县稻虾生态产业园",
    nameEn: "Nanxian Rice-Shrimp Park",
    category: "modern",
    lat: 29.36,
    lng: 112.40,
    city: "益阳南县",
    description: "全国稻虾综合种养示范区，稻虾米地理标志产品",
    details: "南县是全国稻虾综合种养的标杆，稻虾种养面积超60万亩，年产小龙虾超12万吨。'南县稻虾米'获国家地理标志产品认证，实现了'一水两用、一田双收'的生态循环农业模式。",
    year: "2015年起规模化发展",
    image: IMAGES.nanxianShrimp,
    tags: ["稻虾共作", "地理标志", "生态农业"],
    significance: "全国稻虾综合种养标杆",
  },
  {
    id: "liuyang_rice",
    name: "浏阳永安稻田艺术",
    nameEn: "Liuyang Yongan Rice Art",
    category: "modern",
    lat: 28.16,
    lng: 113.64,
    city: "长沙浏阳",
    description: "大地艺术与现代农业的完美融合，稻田彩绘景观",
    details: "浏阳永安镇利用不同品种水稻的色差，在广阔的稻田中绘制出巨幅图案，将传统农业与现代艺术完美融合。每年吸引大量游客前来观赏，成为农旅融合的典范。",
    year: "2018年起",
    image: IMAGES.liuyangRice,
    tags: ["稻田艺术", "农旅融合", "大地艺术"],
    significance: "农业与艺术融合典范",
  },
  {
    id: "dongting_modern",
    name: "洞庭湖现代农业科技园",
    nameEn: "Dongting Modern Agri-Tech Park",
    category: "modern",
    lat: 29.05,
    lng: 112.90,
    city: "岳阳",
    description: "环洞庭湖智慧农业示范区，数字化精准农业标杆",
    details: "洞庭湖现代农业科技园集成了物联网、大数据、人工智能等前沿技术，实现了从播种到收获的全程数字化管理。园区内无人农机、智能灌溉、病虫害AI监测等技术广泛应用，是湖南智慧农业的标杆。",
    year: "2020年建成",
    image: IMAGES.dongtingModern,
    tags: ["智慧农业", "物联网", "精准农业"],
    significance: "湖南智慧农业标杆",
  },
  {
    id: "tea_culture",
    name: "安化黑茶文化产业园",
    nameEn: "Anhua Dark Tea Cultural Park",
    category: "modern",
    lat: 28.38,
    lng: 111.22,
    city: "益阳安化",
    description: "千年黑茶文化传承地，国家级非遗技艺",
    details: "安化黑茶历史悠久，是中国黑茶的发源地。安化千两茶制作技艺被列入国家级非物质文化遗产名录。产业园集茶叶种植、加工、文化展示、旅游体验于一体，年产值超200亿元。",
    year: "茶史逾千年",
    image: IMAGES.teaGarden,
    tags: ["黑茶文化", "国家级非遗", "茶旅融合"],
    significance: "中国黑茶发源地",
  },
  {
    id: "drone_base",
    name: "岳麓区智慧农业无人机基地",
    nameEn: "Yuelu Smart Agri-Drone Base",
    category: "modern",
    lat: 28.18,
    lng: 112.88,
    city: "长沙岳麓",
    description: "农业无人机研发与应用示范基地",
    details: "该基地是湖南省农业无人机技术研发和推广应用的核心平台，集成了植保无人机、巡检无人机、播种无人机等多种机型，服务面积覆盖全省数百万亩农田。",
    year: "2021年",
    image: IMAGES.droneFarming,
    tags: ["无人机", "智慧农业", "科技创新"],
    significance: "农业无人机技术推广平台",
  },
  {
    id: "harvest_fest",
    name: "中国农民丰收节湖南主场",
    nameEn: "China Farmers' Harvest Festival Hunan",
    category: "modern",
    lat: 28.23,
    lng: 112.94,
    city: "长沙",
    description: "每年秋分举办的全国性农业庆典活动湖南主场",
    details: "中国农民丰收节是经国务院批准设立的国家级节日，每年秋分举行。湖南作为农业大省，丰收节主场活动规模盛大，展示湖南农业成就、农耕文化和乡村振兴成果。",
    year: "2018年起每年举办",
    image: IMAGES.harvestFestival,
    tags: ["丰收节", "农业庆典", "文化活动"],
    significance: "国家级农业文化庆典",
  },
  {
    id: "beautiful_village",
    name: "十八洞村",
    nameEn: "Shibadong Village",
    category: "modern",
    lat: 28.30,
    lng: 109.68,
    city: "湘西花垣",
    description: "精准扶贫首倡地，乡村振兴典范",
    details: "十八洞村是'精准扶贫'重要理念的首倡地。通过发展特色种植、乡村旅游等产业，实现了从深度贫困到全面小康的历史性跨越，成为中国乡村振兴的标杆和名片。",
    year: "2013年",
    image: IMAGES.beautifulVillage,
    tags: ["精准扶贫", "乡村振兴", "特色产业"],
    significance: "精准扶贫首倡地",
  },

  // ===== 红色农事旧址 =====
  {
    id: "shaoshan",
    name: "韶山毛泽东劳动实践地",
    nameEn: "Shaoshan Mao Zedong Labor Site",
    category: "red",
    lat: 27.91,
    lng: 112.49,
    city: "湘潭韶山",
    description: "毛泽东少年时期劳动实践之地，红色农耕文化的精神原点",
    details: "韶山是毛泽东的故乡，他在这里度过了童年和少年时代，亲身参与农业劳动。毛泽东故居前的稻田至今保留，成为红色教育和农耕文化体验的重要场所。1927年毛泽东回乡考察农民运动，写下了著名的《湖南农民运动考察报告》。",
    year: "1893-1910年",
    image: IMAGES.shaoshan,
    tags: ["毛泽东故居", "红色教育", "农运考察"],
    significance: "红色农耕文化精神原点",
  },
  {
    id: "sangzhi_granary",
    name: "桑植红二方面军粮仓旧址",
    nameEn: "Sangzhi Red Army Granary",
    category: "red",
    lat: 29.40,
    lng: 110.17,
    city: "张家界桑植",
    description: "红二方面军长征出发地的军粮保障设施",
    details: "桑植是红二方面军长征出发地。红军粮仓旧址见证了革命战争年代军民鱼水情深的历史，当地百姓节衣缩食支援红军，将自家粮食送入粮仓，保障了红军长征的后勤补给。",
    year: "1935年",
    image: IMAGES.sangzhi,
    tags: ["红二方面军", "长征出发地", "军民鱼水情"],
    significance: "红军长征后勤保障见证地",
  },
  {
    id: "huaminglou",
    name: "花明楼刘少奇故里",
    nameEn: "Huaminglou Liu Shaoqi Hometown",
    category: "red",
    lat: 28.02,
    lng: 112.32,
    city: "长沙宁乡",
    description: "刘少奇同志故里，展示其农村调查与农业思想",
    details: "花明楼是刘少奇同志的故乡。刘少奇同志长期关注农业农村问题，1961年回乡调查44天，深入了解农村真实情况，为纠正大跃进中的错误提供了重要依据。",
    year: "1898-1961年",
    image: IMAGES.redHeritage,
    tags: ["刘少奇故里", "农村调查", "红色教育"],
    significance: "领袖农村调查精神的见证",
  },
  {
    id: "qiusc",
    name: "秋收起义文家市会师旧址",
    nameEn: "Autumn Harvest Uprising Site",
    category: "red",
    lat: 28.15,
    lng: 113.75,
    city: "长沙浏阳",
    description: "秋收起义重要会师地，农民革命武装的历史起点",
    details: "1927年9月，毛泽东领导的秋收起义部队在浏阳文家市会师。这次起义以农民为主体，打出了工农革命军的旗帜，标志着中国共产党独立领导武装斗争的开始。",
    year: "1927年",
    image: IMAGES.redHeritage,
    tags: ["秋收起义", "工农革命", "会师旧址"],
    significance: "农民革命武装的历史起点",
  },
  {
    id: "tongdao",
    name: "通道转兵纪念馆",
    nameEn: "Tongdao Turn Memorial",
    category: "red",
    lat: 26.17,
    lng: 109.78,
    city: "怀化通道",
    description: "红军长征转兵之地，侗乡农耕文化与红色记忆交融",
    details: "1934年12月，中央红军在通道召开紧急会议，决定转兵贵州，避免了红军覆灭的危险。通道侗族自治县保留了丰富的侗族农耕文化和红色革命遗迹。",
    year: "1934年",
    image: IMAGES.sangzhi,
    tags: ["长征转兵", "侗族文化", "红色纪念"],
    significance: "红军长征重大转折点",
  },
  {
    id: "datang_site",
    name: "大塘遗址",
    nameEn: "Datang Site",
    category: "ancient",
    lat: 28.06,
    lng: 112.99,
    city: "长沙市",
    description: "湘江流域新石器时代早期文化遗址，距今约7000年。",
    details: "大塘遗址位于长沙市天心区，是湘江流域重要的新石器时代早期遗址。出土了大量陶器和石器，陶器以红陶为主，纹饰多样，反映了较高的制陶工艺。石器以磨制石器为主，有斧、锛、刀、镰等，是早期稻作农业的直接证据。",
    year: "新石器时代",
    image: IMAGES.ancientFarming,
    tags: ["新石器时代", "稻作农业", "大塘文化"],
    significance: "揭示了湘江流域早期农耕文明的发展。",
  },
  {
    id: "bashidang_site",
    name: "八十垱遗址",
    nameEn: "Bashidang Site",
    category: "ancient",
    lat: 29.45,
    lng: 111.75,
    city: "常德市澧县",
    description: "彭头山文化重要遗址，发现了中国最早的古城和人工栽培稻。",
    details: "八十垱遗址位于澧阳平原，是新石器时代早期重要聚落遗址。遗址发现了环绕聚落的围墙和壕沟，是中国已知最早的城址之一。出土了大量稻谷遗存，是世界上最早的人工栽培稻标本之一，对研究稻作农业起源有重要价值。",
    year: "新石器时代",
    image: IMAGES.chengtoushan,
    tags: ["彭头山文化", "最早古城", "稻作起源"],
    significance: "中国早期城址与稻作农业的标杆。",
  },
  {
    id: "tonggushan_site",
    name: "铜鼓山遗址",
    nameEn: "Tonggushan Site",
    category: "ancient",
    lat: 29.46,
    lng: 113.13,
    city: "岳阳市云溪区",
    description: "长江以南商代早期文化遗址，展现了商文化对南方的影响。",
    details: "铜鼓山遗址位于长江南岸，是商代早期盘龙城类型文化的重要遗址。出土了青铜器、玉器和大量陶器，反映了商文化与本地文化的融合。遗址的发现，为研究商代政治、经济和文化向南方的扩张提供了重要实证。",
    year: "商代",
    image: IMAGES.ziquejie,
    tags: ["商代文化", "青铜器", "文化融合"],
    significance: "商代势力南渐的重要见证。",
  },
  {
    id: "liyang_plain_rice_sites",
    name: "澧阳平原稻作遗址群",
    nameEn: "Liyang Plain Rice Cultivation Site Group",
    category: "ancient",
    lat: 29.5,
    lng: 111.78,
    city: "常德市澧县",
    description: "世界稻作农业起源地之一，包含众多史前稻作遗址。",
    details: "澧阳平原是世界公认的稻作农业起源中心之一，分布着从新石器时代早期到晚期的完整稻作遗址序列，包括彭头山、八十垱、城头山等。这些遗址出土了大量稻谷、田块、灌溉系统等遗存，完整展示了稻作农业的起源与发展过程。",
    year: "新石器时代",
    image: IMAGES.yuchanyan,
    tags: ["稻作起源", "世界遗产", "史前聚落"],
    significance: "世界稻作文明的摇篮。",
  },
  {
    id: "tanheli_site",
    name: "炭河里遗址",
    nameEn: "Tanheli Site",
    category: "ancient",
    lat: 28.19,
    lng: 112.23,
    city: "长沙市宁乡市",
    description: "商周时期青铜文化中心，出土了著名的四羊方尊。",
    details: "炭河里遗址是长江以南地区发现的唯一一处西周古城遗址，被誉为‘南中国青铜文化中心’。遗址出土了以四羊方尊为代表的大量青铜器，反映了商周时期高超的青铜铸造技术和独特的祭祀文化。遗址还发现了古城墙、宫殿基址等，为了解南方地区商周时期的社会结构提供了重要线索。",
    year: "商周",
    image: IMAGES.traditionalTools,
    tags: ["商周古城", "青铜文化", "四羊方尊"],
    significance: "商周时期南方青铜文化的杰出代表。",
  },
  {
    id: "laosicheng_site",
    name: "老司城遗址",
    nameEn: "Laosicheng Site",
    category: "ancient",
    lat: 28.99,
    lng: 109.96,
    city: "湘西州永顺县",
    description: "世界文化遗产，土司制度的完整见证，展现了独特的民族农耕文化。",
    details: "老司城遗址是古代溪州彭氏土司政权的司治所在地，是中国规模最大、保存最完整的土司城寨遗址。遗址内有农田、水利设施、祭祀场所等，完整地反映了土司时期的社会生产和生活方式，特别是其独特的山地农耕系统，是土家族人民智慧的结晶。",
    year: "南宋至清",
    image: IMAGES.buffaloPlowing,
    tags: ["世界文化遗产", "土司制度", "山地农耕"],
    significance: "土司制度和民族农耕文化的活化石。",
  },
  {
    id: "yuelu_academy_agricultural_museum",
    name: "岳麓书院农学馆",
    nameEn: "Yuelu Academy Agricultural Museum",
    category: "ancient",
    lat: 28.19,
    lng: 112.94,
    city: "长沙市岳麓区",
    description: "千年学府中的农学思想摇篮，体现了古代书院对农学的重视。",
    details: "岳麓书院作为中国古代四大书院之一，不仅是儒家思想的传播重镇，也蕴含着丰富的农学思想。书院的学规、租田制度以及学者们的著述中，都体现了对农业生产的关注和研究。农学馆的设立，旨在系统整理和展示书院历史上的农学成就，传承经世致用的优良学风。",
    year: "宋代至今",
    image: IMAGES.xiangxiTerrace,
    tags: ["千年学府", "经世致用", "农学思想"],
    significance: "古代书院农学研究的典范。",
  },
  {
    id: "wuxi_cliff_carvings_agricultural_records",
    name: "浯溪摩崖石刻农事记载",
    nameEn: "Wuxi Cliff Carvings Agricultural Records",
    category: "ancient",
    lat: 26.59,
    lng: 111.96,
    city: "永州市祁阳市",
    description: "唐代文学家元结所作《浯溪铭》，记录了当时的农耕生活与思想。",
    details: "浯溪摩崖石刻中，唐代著名文学家元结的《浯溪铭》及其诗文，不仅是书法艺术的瑰宝，也生动记录了唐代安史之乱后，作者归隐田园、劝课农桑的生活。石刻内容涉及农时、作物、耕作方式等，是研究唐代社会经济和农耕文化的重要文献资料。",
    year: "唐代",
    image: IMAGES.ancientFarming,
    tags: ["摩崖石刻", "唐代农事", "元结"],
    significance: "唐代农耕生活的真实写照。",
  },
  {
    id: "longshan_liye_qin_slips_agricultural_records",
    name: "龙山里耶秦简农事记录",
    nameEn: "Longshan Liye Qin Slips Agricultural Records",
    category: "ancient",
    lat: 28.79,
    lng: 109.3,
    city: "湘西州龙山县",
    description: "秦代县级政府档案，详细记录了秦朝的农业管理制度。",
    details: "里耶秦简是秦代迁陵县的官方档案，内容涉及户籍、田亩、赋税、仓储、徭役等方方面面，是研究秦代社会经济的‘百科全书’。其中大量关于农业生产和管理的记录，如土地开垦、作物种植、赋税征收等，为了解秦朝大一统背景下的基层农业运作提供了第一手资料。",
    year: "秦代",
    image: IMAGES.chengtoushan,
    tags: ["秦代简牍", "农业制度", "基层档案"],
    significance: "秦代农业管理制度的生动再现。",
  },
  {
    id: "yongshun_laosicheng_tusi_farming",
    name: "永顺老司城土司农耕",
    nameEn: "Yongshun Laosicheng Tusi Farming",
    category: "ancient",
    lat: 29.0,
    lng: 109.97,
    city: "湘西州永顺县",
    description: "世界文化遗产地独特的农耕体系，展现了土家族的农业智慧。",
    details: "老司城遗址不仅是土司制度的见证，其周边至今仍在使用的梯田、水利灌溉系统和独特的村寨布局，构成了活态的土司农耕文化景观。这种适应山地环境、将生产与生活、军事防御相结合的农耕模式，是土家族人民长期实践的结晶，具有重要的历史和现实意义。",
    year: "南宋至清",
    image: IMAGES.ziquejie,
    tags: ["土司农耕", "活态遗产", "梯田系统"],
    significance: "山地民族适应性农耕体系的典范。",
  },
  {
    id: "lingling_ancient_paddy_fields",
    name: "零陵古稻田",
    nameEn: "Lingling Ancient Paddy Fields",
    category: "ancient",
    lat: 26.22,
    lng: 111.62,
    city: "永州市零陵区",
    description: "历史悠久的稻作区，传承着古老的耕作技术与稻种资源。",
    details: "零陵自古便是湖南重要的稻米产区，拥有悠久的稻作历史。区域内发现的古稻田遗迹，以及流传至今的传统耕作方式和地方稻种，构成了珍贵的农业文化遗产。这些古稻田不仅是历史的见证，也为现代农业的可持续发展提供了宝贵的基因库和经验借鉴。",
    year: "古代",
    image: IMAGES.yuchanyan,
    tags: ["古稻田", "稻种资源", "传统耕作"],
    significance: "传统稻作农业的活态博物馆。",
  },
  {
    id: "hengshan_nanyue_ancient_tea_garden",
    name: "衡山南岳古茶园",
    nameEn: "Hengshan Nanyue Ancient Tea Garden",
    category: "ancient",
    lat: 27.25,
    lng: 112.69,
    city: "衡阳市南岳区",
    description: "千年贡茶产地，拥有古老的茶树资源和独特的制茶工艺。",
    details: "南岳衡山自唐代起便是著名的贡茶产区，其‘南岳云雾茶’享誉千年。古茶园内分布着众多古茶树，传承着独特的种植和制作技艺。这里的茶文化与宗教文化、山水文化深度融合，形成了独特的农耕文化景观，是研究中国茶文化历史的宝贵样本。",
    year: "唐代至今",
    image: IMAGES.traditionalTools,
    tags: ["贡茶文化", "古茶树", "南岳云雾茶"],
    significance: "中国茶文化与宗教文化融合的典范。",
  },
  {
    id: "linli_kemu_mountain_site",
    name: "临澧刻木山遗址",
    nameEn: "Linli Kemu Mountain Site",
    category: "ancient",
    lat: 29.63,
    lng: 111.48,
    city: "常德市临澧县",
    description: "刻木山流传着“丁兰刻木”的孝道故事，是重要的民间文学发源地。",
    details: "刻木山遗址位于临澧县官亭乡，不仅是民间传说“丁兰刻木”的发生地，还包含了丰富的东周时期文化遗产。山下的九里楚墓群是全国规模最大的古墓群之一，反映了古代该区域的社会结构与丧葬习俗。该遗址将孝道文化与楚文化融为一体，是研究古代社会伦理和区域历史的重要样本。",
    year: "东周",
    image: IMAGES.buffaloPlowing,
    tags: ["孝道文化", "楚墓群", "民间文学"],
    significance: "孝道文化与楚文化交融的典范",
  },
  {
    id: "shimen_zaoshi_site",
    name: "石门皂市遗址",
    nameEn: "Shimen Zaoshi Site",
    category: "ancient",
    lat: 29.59,
    lng: 111.38,
    city: "常德市石门县",
    description: "皂市遗址是长江中游新石器时代文化发展的重要标尺。",
    details: "位于石门县的皂市遗址，距今约6900-7200年，是构建长江中游新石器时代文化发展谱系的关键。遗址出土了大量新石器时代遗存，并且发现了晚期智人化石“石门人化石”，对于研究区域史前人类的演化和文化序列具有极高的学术价值。",
    year: "新石器时代",
    image: IMAGES.xiangxiTerrace,
    tags: ["新石器时代", "石门人化石", "史前文化"],
    significance: "构建长江中游史前文化谱系的关键",
  },
  {
    id: "anxiang_tangjiagang_site",
    name: "安乡汤家岗遗址",
    nameEn: "Anxiang Tangjiagang Site",
    category: "ancient",
    lat: 29.41,
    lng: 112.17,
    city: "常德市安乡县",
    description: "汤家岗遗址是长江中游新石器时代的典型原始文化遗址。",
    details: "汤家岗遗址位于安乡县，距今约7000年，总面积约4万平方米。作为长江中游新石器时代的典型，它出土了上千件石器、陶器，其中包括一件标志性的陶塑，为研究当时社会的生产、生活和艺术水平提供了宝贵物证。遗址的发掘对于理解洞庭湖地区的史前文化面貌至关重要。",
    year: "新石器时代",
    image: IMAGES.ancientFarming,
    tags: ["原始文化", "陶器", "洞庭湖区"],
    significance: "洞庭湖区史前文化的宝贵物证",
  },
  {
    id: "taoyuan_cailingcheng_site",
    name: "桃源采菱城遗址",
    nameEn: "Taoyuan Cailingcheng Site",
    category: "ancient",
    lat: 28.91,
    lng: 111.48,
    city: "常德市桃源县",
    description: "采菱城遗址是商周时期沅水流域的重要古城遗址。",
    details: "采菱城遗址位于桃源县，是商周时期沅水流域的一处重要古城。遗址规模宏大，有城墙和护城河遗迹，城内发现了房址、墓葬和大量陶器、石器等遗物。它对于研究沅水流域商周时期的政治、经济、文化以及聚落形态具有重要价值，是探索区域文明进程的珍贵实例。",
    year: "商周",
    image: IMAGES.chengtoushan,
    tags: ["古城遗址", "沅水流域", "商周文化"],
    significance: "沅水流域商周文明的重要见证",
  },
  {
    id: "yuanling_yaotou_site",
    name: "沅陵窑头遗址",
    nameEn: "Yuanling Yaotou Site",
    category: "ancient",
    lat: 28.45,
    lng: 110.39,
    city: "怀化市沅陵县",
    description: "窑头遗址是六朝至唐代时期重要的青瓷窑址群。",
    details: "沅陵窑头遗址位于沅陵县，是一处规模宏大的六朝至唐代青瓷窑址群。遗址发现了多条龙窑遗迹，出土了大量青瓷器物，器形丰富，釉色精美。这处窑址群的发现，填补了湘西地区早期青瓷烧造历史的空白，对于研究中国古代陶瓷史，特别是青瓷的传播与发展具有重要意义。",
    year: "六朝至唐代",
    image: IMAGES.ziquejie,
    tags: ["青瓷窑址", "龙窑", "陶瓷史"],
    significance: "湘西地区早期青瓷烧造的代表",
  },
  {
    id: "mayang_gaocun_site",
    name: "麻阳高村遗址",
    nameEn: "Mayang Gaocun Site",
    category: "ancient",
    lat: 27.87,
    lng: 109.79,
    city: "怀化市麻阳县",
    description: "高村遗址是新石器时代晚期至商周时期的重要聚落遗址。",
    details: "麻阳高村遗址是一处延续时间较长的大型聚落遗址，涵盖了新石器时代晚期至商周时期的文化堆积。遗址内发现了房址、灰坑、墓葬等丰富遗迹，出土了大量陶器、石器和少量青铜器。它为了解湘西地区史前至青铜时代的社会发展、文化交流和生业形态提供了系统性的考古资料。",
    year: "新石器时代晚期至商周",
    image: IMAGES.yuchanyan,
    tags: ["聚落遗址", "文化交流", "青铜时代"],
    significance: "湘西地区史前社会发展的缩影",
  },
  {
    id: "jingzhou_feishan_ancient_terraces",
    name: "靖州飞山古梯田",
    nameEn: "Jingzhou Feishan Ancient Terraces",
    category: "ancient",
    lat: 26.58,
    lng: 109.69,
    city: "怀化市靖州县",
    description: "飞山古梯田是苗侗人民智慧的结晶，展现了独特的山地农耕景观。",
    details: "靖州飞山古梯田是苗、侗等少数民族人民在长期的生产实践中创造的山地农耕奇观。这些梯田顺着山势层层叠叠，从山脚盘绕至山顶，线条优美，气势磅礴。它不仅解决了山区土地稀少的问题，还形成了一套可持续的生态农业系统，是人与自然和谐共生的典范，承载着深厚的民族文化。",
    year: "宋代至今",
    image: IMAGES.traditionalTools,
    tags: ["梯田农耕", "少数民族", "农业遗产"],
    significance: "人与自然和谐共生的山地杰作",
  },
  {
    id: "xinhua_ziquejie_ancient_villages",
    name: "新化紫鹊界周边古村落",
    nameEn: "Xinhua Ziquejie Surrounding Ancient Villages",
    category: "ancient",
    lat: 27.1,
    lng: 111.28,
    city: "娄底市新化县",
    description: "紫鹊界周边的古村落群是梯田农耕文化的活态载体。",
    details: "在新化紫鹊界梯田的核心区周边，散布着众多历史悠久的古村落。这些村落依山而建，与梯田景观融为一体，保留了传统的建筑风格和耕读传家的文化传统。村民们至今仍在梯田上耕作，传承着古老的农耕技艺和民俗活动，构成了“山、水、田、村、人”和谐共生的完整农耕文化生态系统。",
    year: "明清",
    image: IMAGES.buffaloPlowing,
    tags: ["古村落", "耕读文化", "活态遗产"],
    significance: "梯田农耕文化的活态博物馆",
  },
  {
    id: "shaoyang_langshan_ancient_farming_area",
    name: "邵阳崀山古农耕区",
    nameEn: "Shaoyang Langshan Ancient Farming Area",
    category: "ancient",
    lat: 26.39,
    lng: 110.15,
    city: "邵阳市新宁县",
    description: "崀山古农耕区是丹霞地貌与传统农业完美结合的独特区域。",
    details: "邵阳崀山不仅以其独特的丹霞地貌闻名，其间的谷地和缓坡也孕育了历史悠久的农耕文化。这里的古农耕区将农业生产活动巧妙地融入到奇特的自然景观之中，形成了“景中有田，田中有景”的独特风貌。它展示了古代人民利用和改造自然的高度智慧，是研究丹霞地貌区人类活动的重要案例。",
    year: "宋代",
    image: IMAGES.xiangxiTerrace,
    tags: ["丹霞地貌", "生态农业", "景观融合"],
    significance: "丹霞地貌与农耕文化的完美融合",
  },
  {
    id: "shuangfeng_zengguofan_hometown_farming_culture",
    name: "双峰曾国藩故里农耕文化",
    nameEn: "Shuangfeng Zeng Guofan's Hometown Farming Culture",
    category: "ancient",
    lat: 27.45,
    lng: 112.18,
    city: "娄底市双峰县",
    description: "曾国藩故里展现了晚清湘中地区耕读传家的典型农耕文化。",
    details: "曾国藩故里不仅是重要的历史人物纪念地，也完整保留了晚清湘中地区典型的庄园式农耕经济形态。富厚堂周围的田地、池塘、水井等共同构成了一个自给自足的农业生态系统。曾国藩的家训中也包含了大量关于农耕、节俭的内容，是研究近代乡绅家族与农业经济关系的生动实例。",
    year: "清代",
    image: IMAGES.ancientFarming,
    tags: ["耕读传家", "乡绅经济", "近代农业"],
    significance: "晚清湘中乡绅农耕经济的样本",
  },
  {
    id: "xiangyin_zuozongtang_hometown_sericulture_relics",
    name: "湘阴左宗棠故里农桑遗迹",
    nameEn: "Xiangyin Zuo Zongtang's Hometown Sericulture Relics",
    category: "ancient",
    lat: 28.69,
    lng: 112.9,
    city: "岳阳市湘阴县",
    description: "左宗棠故里保留了其倡导的桑蚕养殖等农业改良实践遗迹。",
    details: "晚清名臣左宗棠在其故里湘阴积极倡导农业改良，特别是桑蚕养殖和棉花种植。如今，在其故居周边仍可寻觅到当年推广的桑树种植园、养蚕作坊等遗迹。这些农桑遗迹不仅是左宗棠经世致用思想的体现，也反映了近代中国寻求农业自强的努力，是研究近代农业技术改良史的重要物证。",
    year: "清代",
    image: IMAGES.chengtoushan,
    tags: ["农桑并重", "农业改良", "经世致用"],
    significance: "近代中国农业改良思想的实践",
  },
  {
    id: "youxian_ancient_rice_seed_conservation_area",
    name: "攸县古稻种保护区",
    nameEn: "Youxian Ancient Rice Seed Conservation Area",
    category: "ancient",
    lat: 27.05,
    lng: 113.33,
    city: "株洲市攸县",
    description: "攸县是重要的古稻种资源地，致力于保护和传承农耕基因。",
    details: "攸县地处罗霄山脉，拥有丰富的古稻种资源，是湖南重要的农业遗传多样性宝库。当地建立了古稻种保护区，系统性地对地方特色稻种进行收集、鉴定和保护，并鼓励农民继续种植。这不仅保护了珍贵的农业基因，也传承了与之相关的传统耕作知识和农俗文化，对保障国家粮食安全具有长远意义。",
    year: "古代至今",
    image: IMAGES.ziquejie,
    tags: ["稻种资源", "基因宝库", "农业遗产"],
    significance: "守护农业遗传多样性的活基因库",
  },
  {
    id: "liling_ancient_kiln_agricultural_pottery",
    name: "醴陵古窑农耕陶器",
    nameEn: "Liling Ancient Kiln Agricultural Pottery",
    category: "ancient",
    lat: 27.67,
    lng: 113.5,
    city: "株洲市醴陵市",
    description: "醴陵窑自唐代起便烧制农用陶器，是古代农耕经济的重要组成部分。",
    details: "醴陵窑是中国古代著名的瓷窑之一，其历史可追溯至唐代。除了精美的生活瓷器，醴陵窑也大量生产与农业生产息息相关的陶器，如储粮罐、盛水器、以及各类祭祀用品。这些陶器造型古朴，装饰简洁，反映了古代湖湘地区农耕社会的生产方式、生活习惯和审美情趣，是研究当地农耕文化与陶瓷手工业结合的珍贵实物资料。",
    year: "唐代至清代",
    image: IMAGES.yuchanyan,
    tags: ["陶瓷窑址", "农用陶器", "手工业"],
    significance: "农耕与陶瓷工艺结合典范",
  },
  {
    id: "rucheng_ancestral_hall_farming_murals",
    name: "汝城古祠堂农事壁画",
    nameEn: "Rucheng Ancestral Hall Farming Murals",
    category: "ancient",
    lat: 25.56,
    lng: 113.68,
    city: "郴州市汝城县",
    description: "汝城古祠堂群中保存着大量描绘古代农耕场景的壁画，生动再现了农事活动。",
    details: "汝城县拥有湖南省规模最大、保存最完好的古祠堂群。在这些明清时期的建筑中，许多厅堂的墙壁上绘有精美的壁画。其中，以农事为主题的壁画尤为引人注目，内容涵盖了犁田、插秧、灌溉、收割、打谷等完整流程，人物形象生动，构图饱满，不仅是珍贵的艺术品，更是研究明清时期湘南地区农业技术、社会风俗和民间信仰的直观图像档案。",
    year: "明清时期",
    image: IMAGES.traditionalTools,
    tags: ["古建筑", "壁画艺术", "农事图像"],
    significance: "古代农耕活动的生动图解",
  },
  {
    id: "guiyang_ancient_mining_farming_site",
    name: "桂阳古矿冶农耕遗址",
    nameEn: "Guiyang Ancient Mining and Farming Site",
    category: "ancient",
    lat: 25.76,
    lng: 112.72,
    city: "郴州市桂阳县",
    description: "桂阳自汉代起便是重要的矿冶中心，形成了独特的矿冶与农耕共生文化景观。",
    details: "桂阳县素有‘千年矿都’之称，其采矿和冶炼历史悠久。在古代，矿冶活动与农业生产紧密相连，矿工多为半工半农，形成了独特的社会结构和聚落形态。遗址区域内不仅发现了古代矿洞、冶炼作坊，还伴随着为供应矿区而形成的梯田、灌溉系统和古村落，展现了一幅矿冶手工业与传统农业相互依存、共同发展的历史画卷。",
    year: "汉代至明清",
    image: IMAGES.buffaloPlowing,
    tags: ["矿冶遗址", "农矿共生", "古代经济"],
    significance: "矿冶与农耕结合的独特模式",
  },
  {
    id: "yizhang_mangshan_ancient_tea_trees",
    name: "宜章莽山古茶树群",
    nameEn: "Yizhang Mangshan Ancient Tea Trees",
    category: "ancient",
    lat: 25.05,
    lng: 112.93,
    city: "郴州市宜章县",
    description: "莽山国家森林公园内生长着大片野生古茶树，是茶叶种植历史的活化石。",
    details: "在宜章县莽山原始森林中，发现了树龄达数百上千年的野生古茶树群落。这些古茶树是现代栽培茶树的祖先，具有极高的遗传多样性和科研价值。它们的存在证明了湖南是茶树的原产地之一，也见证了从野生采集到人工栽培的茶叶利用历史变迁。这片古茶树群是研究茶文化起源、茶叶品种演化和古代生态环境的宝贵自然遗产。",
    year: "古代",
    image: IMAGES.xiangxiTerrace,
    tags: ["古茶树", "茶叶起源", "自然遗产"],
    significance: "见证茶叶种植史的活化石",
  },
  {
    id: "jiahe_ancient_paddy_field_site",
    name: "嘉禾古稻田遗址",
    nameEn: "Jiahe Ancient Paddy Field Site",
    category: "ancient",
    lat: 25.58,
    lng: 112.37,
    city: "郴州市嘉禾县",
    description: "嘉禾县发现的古代稻田系统，展示了精巧的灌溉技术和悠久的稻作历史。",
    details: "嘉禾县历史悠久，享有‘禾仓堡’之美誉。考古发现的古稻田遗址，其田埂、沟渠和蓄水池系统布局合理，结构科学，反映了古代劳动人民高超的农田水利建设水平。这些遗址与当地流传的‘神农教耕’传说相呼应，为研究湘南地区史前及历史时期的稻作农业技术、土地利用方式和社会发展提供了直接的考古学证据。",
    year: "史前至宋代",
    image: IMAGES.ancientFarming,
    tags: ["稻作遗址", "农田水利", "神农文化"],
    significance: "古代稻作农业技术的实证",
  },
  {
    id: "lanshan_ancient_rice_cultivation_relics",
    name: "蓝山古稻作遗迹",
    nameEn: "Lanshan Ancient Rice Cultivation Relics",
    category: "ancient",
    lat: 25.23,
    lng: 112.18,
    city: "永州市蓝山县",
    description: "蓝山县境内发现的早期稻作文化遗存，为了解稻作农业起源提供了重要线索。",
    details: "蓝山县位于南岭山区，其独特的地理环境为保存早期人类活动遗迹创造了条件。境内发现的与古稻作相关的石器、陶器以及可能的田块遗迹，表明这里在新石器时代晚期可能已存在原始的稻作农业。这些遗迹对于探讨稻作农业在华南地区的起源、传播路径以及对早期社会文明进程的影响具有重要的学术价值。",
    year: "新石器时代",
    image: IMAGES.chengtoushan,
    tags: ["稻作起源", "史前农业", "南岭文化"],
    significance: "探索华南稻作农业的起源",
  },
  {
    id: "jiangyong_nushu_farming_records",
    name: "江永女书中的农事记载",
    nameEn: "Farming Records in Jiangyong's Nüshu (Women's Script)",
    category: "ancient",
    lat: 25.43,
    lng: 111.47,
    city: "永州市江永县",
    description: "世界唯一的女性文字‘女书’中，包含了大量关于农耕活动和女性农事的诗歌。",
    details: "江永女书是世界上独一无二的女性专用文字。在其传承下来的诗歌、书信等作品中，有相当一部分内容是描绘和吟唱当地的农事活动，如种棉纺纱、养蚕缫丝、插秧唱歌等。这些记载不仅反映了具体的农耕技术和流程，更从女性的独特视角展现了她们在农业生产中的辛勤劳动、生活情感和社群交往，是研究古代性别分工和乡村社会生活的珍贵文献。",
    year: "明清时期",
    image: IMAGES.ziquejie,
    tags: ["非物质文化遗产", "女书", "女性农事"],
    significance: "女性视角的古代农耕记录",
  },
  {
    id: "xintian_ancient_farming_stone_carvings",
    name: "新田古农耕石刻",
    nameEn: "Xintian Ancient Farming Stone Carvings",
    category: "ancient",
    lat: 25.91,
    lng: 112.22,
    city: "永州市新田县",
    description: "新田县发现的古代石刻中，部分图像被解读为与农耕祭祀或天文历法相关。",
    details: "新田县历史文化底蕴深厚，境内散布着众多古代石刻。其中一些年代久远、图案抽象的石刻引起了学者们的关注。有研究认为，这些石刻上的符号可能记录了古代先民对天象的观察，用以指导农时，或是用于农耕祭祀仪式。它们是古代农耕社会精神文化生活的物证，对于研究天文历法与农业的结合、早期宗教信仰具有重要意义。",
    year: "史前至汉代",
    image: IMAGES.yuchanyan,
    tags: ["石刻艺术", "农耕祭祀", "天文历法"],
    significance: "古代天文与农业结合的物证",
  },
  {
    id: "qiyang_wuxi_farming_steles",
    name: "祁阳浯溪古农耕碑刻",
    nameEn: "Qiyang Wuxi Ancient Farming Steles",
    category: "ancient",
    lat: 26.58,
    lng: 111.85,
    city: "永州市祁阳市",
    description: "浯溪碑林中保存有唐宋时期关于劝农、水利和租佃制度的碑刻。",
    details: "祁阳浯溪碑林是中国南方最大的露天碑林，摩崖石刻琳琅满目。其中，除了文学艺术作品，还包含了一些极具史料价值的官方文告和记录。例如，唐代颜真卿所书《大唐中兴颂》的崖壁附近，就有关于地方官劝课农桑、兴修水利、以及记录田亩租佃关系的碑刻。这些碑刻是研究唐宋时期土地制度、农业管理和社会经济的第一手资料。",
    year: "唐宋时期",
    image: IMAGES.traditionalTools,
    tags: ["碑刻文化", "农业政策", "土地制度"],
    significance: "唐宋农业管理制度的实录",
  },
  {
    id: "dongan_ancient_waterwheel_clusters",
    name: "东安古水车群",
    nameEn: "Dongan Ancient Waterwheel Clusters",
    category: "ancient",
    lat: 26.4,
    lng: 111.29,
    city: "永州市东安县",
    description: "东安县至今仍保留着古老的水车群，是传统农田灌溉智慧的活态展示。",
    details: "东安县的河流沿岸，至今仍能看到数十架巨大的木质水车在缓缓转动，将河水提升至高处灌溉农田。这种被称为‘筒车’的灌溉工具自唐代发明以来，在中国南方广泛使用。东安的水车群规模宏大，结构完整，部分仍在发挥实际作用，构成了独特的田园景观。它们是古代农业工程技术的杰出典范，也是人与自然和谐共生的农耕智慧的活态遗产。",
    year: "宋代至今",
    image: IMAGES.buffaloPlowing,
    tags: ["灌溉工程", "农业遗产", "活态文化"],
    significance: "古代农田灌溉智慧的活化石",
  },
  {
    id: "lengshuijiang_ancient_tin_mine_farming_site",
    name: "冷水江古锡矿农耕遗址",
    nameEn: "Lengshuijiang Ancient Tin Mine and Farming Site",
    category: "ancient",
    lat: 27.69,
    lng: 111.44,
    city: "娄底市冷水江市",
    description: "世界‘锑都’冷水江的锡矿山，自古便有采矿与农耕并存的历史。",
    details: "冷水江市锡矿山以锑矿闻名于世，但其采矿史可追溯至明清时期的锡矿开采。与桂阳类似，这里的矿冶活动也催生了农矿共生的聚落。在矿区周边，形成了为矿工提供粮食蔬菜的农业区，至今仍可见古道、梯田和村落遗址。这些遗迹共同构成了工业文明与农业文明交融的独特文化景观，见证了近代工业兴起前夜的社会经济形态。",
    year: "明清时期",
    image: IMAGES.xiangxiTerrace,
    tags: ["矿冶遗址", "工业遗产", "农矿共生"],
    significance: "工业文明前的农矿交融景观",
  },
  {
    id: "lianyuan_ancient_terrace_clusters",
    name: "涟源古梯田群",
    nameEn: "Lianyuan Ancient Terrace Clusters",
    category: "ancient",
    lat: 27.7,
    lng: 111.67,
    city: "娄底市涟源市",
    description: "涟源市山区分布着形态优美的古梯田群，是山区人民改造自然的杰作。",
    details: "与紫鹊界梯田相似，涟源市的龙山、湄江等地也分布着大片历史悠久的梯田。这些梯田顺着山势层层叠叠，线条优美，规模宏大，展现了山区人民‘垦山为田’的非凡智慧和坚韧毅力。它们不仅是重要的农业生产设施，解决了山区的粮食问题，也形成了人与自然和谐共生的壮丽景观，是湖湘农耕文化中山地农业模式的典型代表。",
    year: "宋元至今",
    image: IMAGES.ancientFarming,
    tags: ["梯田景观", "山地农业", "农业遗产"],
    significance: "湖湘山地农耕文明的代表",
  },
  {
    id: "changde_liuyehu_modern_agriculture_park",
    name: "常德柳叶湖现代农业园",
    nameEn: "Changde Liuye Lake Modern Agriculture Park",
    category: "modern",
    lat: 29.08,
    lng: 111.73,
    city: "常德",
    description: "集生态农业、观光旅游、科普教育于一体的综合性现代农业园区。",
    details: "常德柳叶湖现代农业园依托柳叶湖优美的自然风光，大力发展智慧农业和生态旅游。园区引进了多种现代农业技术，建设了智能温室、无土栽培区和有机果蔬采摘园，实现了农业生产的标准化和智能化。游客在此不仅可以体验农耕乐趣，还能享受到高品质的休闲度假服务。",
    year: "1998",
    image: IMAGES.teaGarden,
    tags: ["智慧农业", "生态旅游", "农旅融合"],
    significance: "引领区域现代农业发展。",
  },
  {
    id: "yueyang_junshan_silver_needle_tea_garden",
    name: "岳阳君山银针茶园",
    nameEn: "Yueyang Junshan Silver Needle Tea Garden",
    category: "modern",
    lat: 29.46,
    lng: 113.01,
    city: "岳阳",
    description: "中国黄茶之乡，以独特的‘闷黄’工艺闻名。",
    details: "岳阳君山银针茶园位于洞庭湖中的君山岛，是中国十大名茶之一君山银针的原产地。茶园拥有得天独厚的生态环境，传承了千年的贡茶制作技艺。其核心工艺‘闷黄’技术，使茶叶形成了独特的色香味，被誉为‘金镶玉’。该产业园不仅是重要的茶叶生产基地，也是集茶文化体验、科研和旅游于一体的综合性园区。",
    year: "2011",
    image: IMAGES.harvestFestival,
    tags: ["黄茶", "地理标志", "茶旅融合"],
    significance: "传承千年贡茶制作技艺。",
  },
  {
    id: "zhangjiajie_mei_tea_base",
    name: "张家界莓茶基地",
    nameEn: "Zhangjiajie Mei Tea Base",
    category: "modern",
    lat: 29.13,
    lng: 110.48,
    city: "张家界",
    description: "全国最大的莓茶生产基地，富含黄酮的特色健康茶饮。",
    details: "张家界莓茶基地位于武陵山脉腹地，是全国最大的莓茶种植和加工基地。莓茶是一种富含天然黄酮的植物，具有独特的保健功效。当地采用‘公司+合作社+基地+农户’的模式，将莓茶产业发展成为带动地方经济和农民增收的支柱产业，并结合旅游资源，打造集种植、加工、科研、康养于一体的莓茶文化产业链。",
    year: "2013",
    image: IMAGES.beautifulVillage,
    tags: ["莓茶", "健康养生", "产业扶贫"],
    significance: "打造中国莓茶之乡品牌。",
  },
  {
    id: "xiangxi_kiwi_fruit_industrial_park",
    name: "湘西猕猴桃产业园",
    nameEn: "Xiangxi Kiwi Fruit Industrial Park",
    category: "modern",
    lat: 28.31,
    lng: 109.74,
    city: "湘西",
    description: "全球最大的富硒猕猴桃产业基地，助力乡村振兴。",
    details: "湘西州依托其独特的富硒土壤和气候条件，自1996年起大力发展猕猴桃产业，现已成为世界最大的富硒猕猴桃生产基地。产业园覆盖永顺、花垣等多个县市，采用现代化种植技术和‘公司+合作社+农户’的模式，不仅提升了果品质量，也成为当地农民脱贫致富的重要支柱。这里是集种植、研发、加工和销售于一体的全产业链示范区。",
    year: "1996",
    image: IMAGES.dongtingHarvest,
    tags: ["猕猴桃", "富硒农业", "乡村振兴"],
    significance: "全球最大的富硒猕猴桃基地。",
  },
  {
    id: "huaihua_bingtang_orange_base",
    name: "怀化冰糖橙基地",
    nameEn: "Huaihua Bingtang Orange Base",
    category: "modern",
    lat: 27.87,
    lng: 109.8,
    city: "怀化",
    description: "中国冰糖橙之都，果实皮薄汁多，甜润爽口。",
    details: "怀化麻阳是中国冰糖橙的发源地和主产区，被誉为‘中国冰糖橙之都’。麻阳冰糖橙以其皮薄无核、汁多味甜、富含维生素C而闻名。当地通过标准化种植和品牌化运营，将冰糖橙产业发展成为富民强县的支柱产业，并积极推动农旅融合，开发采摘体验游。",
    year: "2001",
    image: IMAGES.modernAgriculture,
    tags: ["冰糖橙", "地理标志", "产业扶贫"],
    significance: "中国冰糖橙之都。",
  },
  {
    id: "yongzhou_lanshan_blueberry_base",
    name: "永州蓝山蓝莓基地",
    nameEn: "Yongzhou Lanshan Blueberry Base",
    category: "modern",
    lat: 25.37,
    lng: 112.2,
    city: "永州",
    description: "高山有机蓝莓种植示范基地，果实饱满，富含花青素。",
    details: "永州蓝山县利用其高海拔、无污染的自然环境优势，发展高山有机蓝莓产业。基地采用标准化种植技术，引进了优良蓝莓品种，果实以其颗粒饱满、口感酸甜、富含花青素而备受市场青睐。蓝山蓝莓基地不仅是重要的经济作物产区，也成为集观光、采摘、科普于一体的农业旅游点，带动了当地乡村旅游的发展。",
    year: "2015",
    image: IMAGES.anjiangRice,
    tags: ["蓝莓", "有机农业", "高山种植"],
    significance: "打造华南高山蓝莓品牌。",
  },
  {
    id: "chenzhou_linwu_duck_breeding_base",
    name: "郴州临武鸭养殖基地",
    nameEn: "Chenzhou Linwu Duck Breeding Base",
    category: "modern",
    lat: 25.28,
    lng: 112.56,
    city: "郴州",
    description: "千年贡品临武鸭，肉质细嫩，味道鲜美。",
    details: "临武鸭养殖历史悠久，可追溯至唐代，曾为朝廷贡品。郴州临武鸭养殖基地依托武水河流域的优良生态环境，采用‘公司+基地+农户’的模式进行标准化、规模化养殖。临武鸭以其独特的生长周期和肉质风味而闻名，现已发展成为集种鸭繁育、商品鸭养殖、饲料生产、屠宰加工和销售于一体的全产业链企业，是当地乡村振兴的龙头产业。",
    year: "1999",
    image: IMAGES.dongtingModern,
    tags: ["临武鸭", "地理标志", "全产业链"],
    significance: "传承千年贡品养殖历史。",
  },
  {
    id: "hengyang_changning_camellia_oleifera_base",
    name: "衡阳常宁油茶基地",
    nameEn: "Hengyang Changning Camellia Oleifera Base",
    category: "modern",
    lat: 26.42,
    lng: 112.4,
    city: "衡阳",
    description: "中国油茶之乡，千年传承，绿色健康。",
    details: "常宁市拥有1700多年的油茶栽培历史，是全国闻名的‘中国油茶之乡’。基地遍布全市多个乡镇，通过科技赋能，对老油茶林进行低产改造，并大力发展高产油茶。常宁油茶以其纯天然、高品质、富含不饱和脂肪酸而著称。当地已形成集种植、加工、销售、科研和旅游于一体的完整产业链，成为推动区域经济发展和乡村振兴的重要力量。",
    year: "2000",
    image: IMAGES.liuyangRice,
    tags: ["油茶", "地理标志", "科技兴农"],
    significance: "全国油茶产业核心产区。",
  },
  {
    id: "shaoyang_shaodong_chinese_herbal_medicine_base",
    name: "邵阳邵东中药材基地",
    nameEn: "Shaoyang Shaodong Chinese Herbal Medicine Base",
    category: "modern",
    lat: 27.26,
    lng: 111.74,
    city: "邵阳",
    description: "千年药都廉桥，全国最大的中药材专业市场之一。",
    details: "邵东市廉桥镇是全国知名的‘南国药都’，拥有全国最大的中药材专业市场之一。基地种植有玉竹、白芍、丹皮等170多种道地药材，其中玉竹种植面积和产量居全国首位，被誉为‘中国玉竹之乡’。当地通过‘市场+基地+农户’的模式，形成了集种植、加工、仓储、物流、交易于一体的完整产业链，是中药材产业的标杆。",
    year: "1996",
    image: IMAGES.nanxianShrimp,
    tags: ["中药材", "廉桥药都", "玉竹之乡"],
    significance: "南国药都，中药材集散地。",
  },
  {
    id: "zhuzhou_yanling_yellow_peach_base",
    name: "株洲炎陵黄桃基地",
    nameEn: "Zhuzhou Yanling Yellow Peach Base",
    category: "modern",
    lat: 26.5,
    lng: 113.77,
    city: "株洲",
    description: "中国优质黄桃之乡，果大形正，香甜可口。",
    details: "炎陵县凭借其得天独厚的生态环境和气候条件，成为‘中国优质黄桃之乡’。炎陵黄桃以其果大、形正、色艳、香浓、味甜的特点而著称，是国家地理标志产品。当地政府大力扶持黄桃产业，通过‘电商+农户’模式，将炎陵黄桃销往全国各地，形成了集种植、加工、销售、旅游于一体的完整产业链，成为当地农民增收致富的‘黄金果’。",
    year: "2007",
    image: IMAGES.droneFarming,
    tags: ["黄桃", "地理标志", "电商助农"],
    significance: "打造中国黄桃第一品牌。",
  },
  {
    id: "loudi_shuangfeng_chili_sauce_industrial_park",
    name: "娄底双峰辣酱产业园",
    nameEn: "Loudi Shuangfeng Chili Sauce Industrial Park",
    category: "modern",
    lat: 27.46,
    lng: 112.18,
    city: "娄底",
    description: "三百余年永丰辣酱，国家地理标志产品。",
    details: "双峰县的永丰辣酱拥有三百多年的制作历史，是国家地理标志保护产品和湖南省非物质文化遗产。产业园以当地特产的红灯笼辣椒为原料，采用传统工艺与现代技术相结合的方式进行生产。通过‘公司+合作社+基地’的模式，带动了周边地区辣椒、小麦等农作物的种植，形成了完整的产业链，成为当地农业增效、农民增收的特色支柱产业。",
    year: "2008",
    image: IMAGES.teaGarden,
    tags: ["永丰辣酱", "非物质文化遗产", "地理标志"],
    significance: "传承三百年辣酱制作工艺。",
  },
  {
    id: "yiyang_taojiang_bamboo_shoot_base",
    name: "益阳桃江竹笋基地",
    nameEn: "Yiyang Taojiang Bamboo Shoot Base",
    category: "modern",
    lat: 28.52,
    lng: 112.16,
    city: "益阳",
    description: "中国竹子之乡，竹林面积广阔，竹笋产业发达。",
    details: "桃江县拥有115万亩竹林，被誉为‘中国竹子之乡’。当地依托丰富的竹资源，大力发展竹笋产业，形成了从鲜笋供应到精深加工的完整产业链。通过建设高产笋用林基地和推广先进的林下经济模式，桃江竹笋不仅产量高、品质好，还带动了当地农民增收和乡村振兴。桃江竹笋产业是绿色生态农业的典范。",
    year: "2005",
    image: IMAGES.harvestFestival,
    tags: ["竹笋", "竹子之乡", "林下经济"],
    significance: "全国重要的竹笋生产基地。",
  },
  {
    id: "changsha_wangcheng_lotus_prawn_base",
    name: "长沙望城荷花虾基地",
    nameEn: "Changsha Wangcheng Lotus Prawn Base",
    category: "modern",
    lat: 28.35,
    lng: 112.82,
    city: "长沙",
    description: "荷塘养虾，生态共养，肉质鲜美。",
    details: "长沙望城区的荷花虾基地首创了‘荷塘+小龙虾’的生态共养模式。利用荷塘的天然环境，为小龙虾提供优质的生长空间，而小龙虾的排泄物又成为荷花的天然肥料。这种模式产出的荷花虾，不仅个大、肉质饱满、味道鲜美，而且更加生态环保。目前，望城荷花虾已成为当地特色农业品牌，带动了乡村旅游和餐饮业的发展。",
    year: "2018",
    image: IMAGES.beautifulVillage,
    tags: ["荷花虾", "生态养殖", "农旅融合"],
    significance: "开创荷塘生态共养新模式。",
  },
  {
    id: "xiangtan_xianglian_industrial_park",
    name: "湘潭湘莲产业园",
    nameEn: "Xiangtan Xianglian Industrial Park",
    category: "modern",
    lat: 27.78,
    lng: 112.95,
    city: "湘潭",
    description: "中国湘莲之乡，全国最大的湘莲集散中心。",
    details: "湘潭县花石镇是闻名全国的‘中国湘莲之乡’，也是全国最大的湘莲生产、加工和贸易集散中心。产业园以‘公司+基地+农户’的模式，带动了全县及周边地区湘莲种植，形成了完整的产业链。这里的湘莲以其粒大饱满、洁白圆润、质地细腻、清香可口而著称，是国家地理标志产品。湘莲产业已成为当地乡村振兴的支柱产业。",
    year: "2019",
    image: IMAGES.dongtingHarvest,
    tags: ["湘莲", "地理标志", "一县一特"],
    significance: "全国最大的湘莲集散中心。",
  },
  {
    id: "yueyang_huarong_mustard_green_industrial_park",
    name: "岳阳华容芥菜产业园",
    nameEn: "Yueyang Huarong Mustard Green Industrial Park",
    category: "modern",
    lat: 29.53,
    lng: 112.54,
    city: "岳阳",
    description: "中国芥菜之乡，全国最大的芥菜生产加工基地。",
    details: "华容县是全国最大的芥菜生产区，素有‘中国芥菜之乡’的美誉。华容芥菜产业园是集芥菜种植、加工、研发、物流、品牌展示于一体的现代农业产业园。通过标准化种植和精深加工，华容芥菜产品远销海内外。该产业园的建设，有力地推动了当地芥菜产业的转型升级，带动了数十万农民增收致富，是乡村产业振兴的典范。",
    year: "2018",
    image: IMAGES.modernAgriculture,
    tags: ["芥菜", "地理标志", "产业集群"],
    significance: "中国芥菜产业的领军者。",
  },
  {
    id: "changde_shimen_citrus_base",
    name: "常德石门柑橘基地",
    nameEn: "Changde Shimen Citrus Base",
    category: "modern",
    lat: 29.58,
    lng: 111.38,
    city: "常德",
    description: "中国柑橘之乡，全国早熟蜜橘第一县。",
    details: "石门县是中国著名的‘柑橘之乡’，尤以早熟蜜橘闻名。基地采用标准化种植和现代化的管理技术，培育出的柑橘果皮薄、果肉多汁、甜度高。通过品牌化运作和拓展线上线下销售渠道，‘石门柑橘’已成为国内外知名的农产品品牌，是当地农民增收致富的‘黄金果’，也是推动县域经济发展的重要引擎。",
    year: "2007",
    image: IMAGES.anjiangRice,
    tags: ["柑橘", "早熟蜜橘", "地理标志"],
    significance: "全国重要的早熟柑橘产区。",
  },
  {
    id: "huaihua_jingzhou_bayberry_base",
    name: "怀化靖州杨梅基地",
    nameEn: "Huaihua Jingzhou Bayberry Base",
    category: "modern",
    lat: 26.58,
    lng: 109.68,
    city: "怀化",
    description: "中国杨梅之乡，种植历史悠久，果实品质优良。",
    details: "靖州县是‘中国杨梅之乡’，杨梅种植历史超过2000年。当地依托得天独厚的自然条件，大力发展杨梅产业，形成了集种植、加工、销售、旅游于一体的全产业链。靖州杨梅以其果大、核小、色艳、味甜而闻名，是国家地理标志产品。杨梅产业已成为当地农民增收和乡村振兴的特色支柱产业。",
    year: "2013",
    image: IMAGES.dongtingModern,
    tags: ["杨梅", "地理标志", "中国杨梅之乡"],
    significance: "中国杨梅之乡，产业富民。",
  },
  {
    id: "zhangjiajie_giant_salamander_breeding_base",
    name: "张家界大鲵养殖基地",
    nameEn: "Zhangjiajie Giant Salamander Breeding Base",
    category: "modern",
    lat: 29.12,
    lng: 110.48,
    city: "张家界",
    description: "中国大鲵之乡，集保护、科研、养殖于一体。",
    details: "张家界是中国大鲵的核心产区，被誉为‘中国大鲵之乡’。大鲵养殖基地采用‘公司+基地+农户’的模式，在保护野生资源的同时，大力发展人工繁育和规模化养殖。基地建立了完善的科研体系，成功实现了大鲵的子三代繁育。如今，张家界大鲵产业已形成集科研、养殖、加工、餐饮和旅游于一体的完整产业链，成为当地特色经济的重要组成部分。",
    year: "2011",
    image: IMAGES.liuyangRice,
    tags: ["大鲵", "娃娃鱼", "特种养殖"],
    significance: "全国最大的大鲵养殖基地。",
  },
  {
    id: "xiangxi_baojing_golden_tea_base",
    name: "湘西保靖黄金茶基地",
    nameEn: "Xiangxi Baojing Golden Tea Base",
    category: "modern",
    lat: 28.71,
    lng: 109.65,
    city: "湘西",
    description: "中国地理标志产品，具有‘四高四绝’的独特品质。",
    details: "保靖黄金茶是古老的特异性茶树种质资源，原产于保靖县。其茶叶氨基酸含量高达7%，是普通绿茶的两倍以上，具有‘香、绿、爽、醇’的特点。当地通过大力发展保靖黄金茶产业，带动了数万茶农增收致富，成为乡村振兴的支柱产业。",
    year: "2019",
    image: IMAGES.nanxianShrimp,
    tags: ["黄金茶", "地理标志", "一县一品"],
    significance: "湘西脱贫致富的‘黄金叶’。",
  },
  {
    id: "yongzhou_jiangyong_pomelo_base",
    name: "永州江永香柚基地",
    nameEn: "Yongzhou Jiangyong Pomelo Base",
    category: "modern",
    lat: 25.27,
    lng: 111.34,
    city: "永州",
    description: "中国香柚之乡，果皮金黄，香气浓郁。",
    details: "江永县是‘中国香柚之乡’，已有数百年栽培历史。江永香柚以其果形美观、色泽金黄、香气浓郁、酸甜适中而闻名。当地通过‘合作社+基地+果户’模式，大力发展香柚产业，并结合电商平台拓宽销售渠道，使香柚成为带动农民增收致富的‘黄金果’，是当地一张靓丽的农业名片。",
    year: "1979",
    image: IMAGES.droneFarming,
    tags: ["香柚", "地理标志", "中国香柚之乡"],
    significance: "中国香柚之乡，富民兴村。",
  },
  {
    id: "chenzhou_rucheng_chili_base",
    name: "郴州汝城辣椒基地",
    nameEn: "Chenzhou Rucheng Chili Base",
    category: "modern",
    lat: 25.54,
    lng: 113.68,
    city: "郴州",
    description: "中国特色农产品优势区，高山生态辣椒品质优良。",
    details: "汝城县利用其独特的亚热带季风湿润气候和山地资源，大力发展高山生态辣椒产业。通过‘公司+基地+农户’模式，建设标准化生产基地，推广绿色防控技术，汝城辣椒以其色泽鲜亮、辣味纯正、肉质厚实而备受市场青睐。辣椒产业已成为当地农民增收、乡村振兴的特色支柱产业。",
    year: "2016",
    image: IMAGES.teaGarden,
    tags: ["辣椒", "高山蔬菜", "地理标志"],
    significance: "湘南地区重要辣椒产区。",
  },
  {
    id: "hengyang_qidong_daylily_base",
    name: "衡阳祁东黄花菜基地",
    nameEn: "Hengyang Qidong Daylily Base",
    category: "modern",
    lat: 26.8,
    lng: 112.09,
    city: "衡阳",
    description: "中国黄花菜之乡，全国最大的黄花菜生产基地。",
    details: "祁东县是‘中国黄花菜之乡’，种植历史超过500年，种植面积和产量均居全国首位。祁东黄花菜以其色泽鲜亮、香气浓郁、肉质肥厚而著称，是国家地理标志产品。当地通过标准化种植和产业化经营，将黄花菜发展成为富民强县的‘黄金菜’，形成了集种植、加工、销售、科研于一体的完整产业链。",
    year: "1998",
    image: IMAGES.harvestFestival,
    tags: ["黄花菜", "地理标志", "中国黄花菜之乡"],
    significance: "全国最大的黄花菜生产基地。",
  },
  {
    id: "shaoyang_wugang_marinated_food_industrial_park",
    name: "邵阳武冈卤菜产业园",
    nameEn: "Shaoyang Wugang Marinated Food Industrial Park",
    category: "modern",
    lat: 26.73,
    lng: 110.63,
    city: "邵阳",
    description: "中国卤菜之都，千年传承，百亿产业集群。",
    details: "武冈卤菜历史悠久，被誉为‘中国卤菜之都’。产业园整合了众多卤制品企业和作坊，采用传统工艺与现代科技相结合的生产模式。园区实行统一原料采购、统一污水处理，推动了产业的标准化和规模化发展，目标是打造百亿级产业集群，是当地富民强市的支柱产业。",
    year: "2021",
    image: IMAGES.beautifulVillage,
    tags: ["卤菜", "中国卤菜之都", "产业集群"],
    significance: "千年卤菜之都，百亿产业集群。",
  },
  {
    id: "changsha_liuyang_flower_and_nursery_stock_base",
    name: "长沙浏阳花卉苗木基地",
    nameEn: "Changsha Liuyang Flower and Nursery Stock Base",
    category: "modern",
    lat: 28.18,
    lng: 113.62,
    city: "长沙市浏阳市",
    description: "全国知名的花卉苗木生产与交易中心。",
    details: "浏阳花卉苗木产业历史悠久，是全国重要的生产和集散地之一。基地规模宏大，品种繁多，集生产、研发、销售、旅游观光于一体，推动了地方经济发展和乡村振兴。",
    year: "1990s",
    image: IMAGES.dongtingHarvest,
    tags: ["花卉苗木", "产业基地", "乡村振兴"],
    significance: "引领全国花木产业",
  },
  {
    id: "zhuzhou_chaling_navel_orange_base",
    name: "株洲茶陵脐橙基地",
    nameEn: "Zhuzhou Chaling Navel Orange Base",
    category: "modern",
    lat: 26.78,
    lng: 113.55,
    city: "株洲市茶陵县",
    description: "以“纽荷尔”脐橙闻名的优质水果产区。",
    details: "茶陵县利用得天独厚的砂质红壤和气候条件，大力发展脐橙产业。所产脐橙果大形正、色泽鲜艳、风味浓郁，深受市场欢迎，成为当地农民增收致富的支柱产业。",
    year: "2000s",
    image: IMAGES.modernAgriculture,
    tags: ["脐橙", "地理标志", "精准扶贫"],
    significance: "湘东优质水果名片",
  },
  {
    id: "xiangtan_shaoshan_red_agritourism_base",
    name: "湘潭韶山红色农旅基地",
    nameEn: "Xiangtan Shaoshan Red Agritourism Base",
    category: "modern",
    lat: 27.91,
    lng: 112.49,
    city: "湘潭市韶山市",
    description: "融合红色文化与现代农业的旅游示范区。",
    details: "基地依托韶山独特的红色文化资源，结合现代农业观光、农事体验和生态休闲，打造出一条独具特色的农旅融合发展路径，实现了社会效益与经济效益的双丰收。",
    year: "2010s",
    image: IMAGES.anjiangRice,
    tags: ["红色旅游", "农旅融合", "韶山精神"],
    significance: "红色文化与农业结合",
  },
  {
    id: "hengyang_leiyang_camellia_oleifera_museum",
    name: "衡阳耒阳油茶博物馆",
    nameEn: "Hengyang Leiyang Camellia Oleifera Museum",
    category: "modern",
    lat: 26.4,
    lng: 112.85,
    city: "衡阳市耒阳市",
    description: "全国首家以油茶文化为主题的博物馆。",
    details: "耒阳是“中国油茶之乡”，该博物馆全面展示了油茶的种植历史、加工工艺、产品应用和文化内涵。它不仅是科普教育的平台，也是推动油茶产业发展的重要窗口。",
    year: "2018",
    image: IMAGES.dongtingModern,
    tags: ["油茶", "专题博物馆", "产业文化"],
    significance: "传承千年油茶文化",
  },
  {
    id: "shaoyang_longhui_honeysuckle_base",
    name: "邵阳隆回金银花基地",
    nameEn: "Shaoyang Longhui Honeysuckle Base",
    category: "modern",
    lat: 27.12,
    lng: 111.05,
    city: "邵阳市隆回县",
    description: "“中国金银花之乡”的核心产区。",
    details: "隆回县金银花种植面积和产量均居全国前列，品质优良。基地通过标准化种植和精深加工，延长了产业链，提升了附加值，成为带动区域经济发展的重要力量。",
    year: "1980s",
    image: IMAGES.liuyangRice,
    tags: ["金银花", "中药材", "地理标志"],
    significance: "全国金银花产业标杆",
  },
  {
    id: "yueyang_pingjiang_sauced_dried_bean_curd_industrial_park",
    name: "岳阳平江酱干产业园",
    nameEn: "Yueyang Pingjiang Sauced Dried Bean Curd Industrial Park",
    category: "modern",
    lat: 28.71,
    lng: 113.58,
    city: "岳阳市平江县",
    description: "传承百年工艺的豆制品加工产业集群。",
    details: "平江酱干是湖南著名特产，历史悠久。产业园集聚了众多知名品牌，通过技术创新和规模化生产，将传统小吃发展成为年产值数十亿的现代化食品产业。",
    year: "2012",
    image: IMAGES.nanxianShrimp,
    tags: ["平江酱干", "传统食品", "产业集群"],
    significance: "地方特产工业化典范",
  },
  {
    id: "changde_taoyuan_leicha_cultural_park",
    name: "常德桃源擂茶文化园",
    nameEn: "Changde Taoyuan Lei Cha (Ground Tea) Cultural Park",
    category: "modern",
    lat: 28.92,
    lng: 111.48,
    city: "常德市桃源县",
    description: "展示和体验桃花源擂茶习俗的文化园区。",
    details: "桃源擂茶是国家级非物质文化遗产。文化园通过实景展示、互动体验和产品展销，系统介绍了擂茶的制作工艺、历史渊源和养生功效，成为传播地方民俗的重要载体。",
    year: "2015",
    image: IMAGES.droneFarming,
    tags: ["擂茶", "非物质文化遗产", "民俗文化"],
    significance: "活态传承非遗文化",
  },
  {
    id: "zhangjiajie_yongding_vine_tea_science_park",
    name: "张家界永定区莓茶科技园",
    nameEn: "Zhangjiajie Yongding District Vine Tea Science and Technology Park",
    category: "modern",
    lat: 29.13,
    lng: 110.48,
    city: "张家界市永定区",
    description: "集莓茶研发、种植和加工于一体的科技园区。",
    details: "莓茶是张家界的特色生物资源。科技园致力于莓茶的品种选育、功效研究和产品开发，通过科技创新提升莓茶产业的附加值，带动了武陵山区特色农业的发展。",
    year: "2016",
    image: IMAGES.teaGarden,
    tags: ["莓茶", "科技农业", "生物资源"],
    significance: "科技赋能特色农业",
  },
  {
    id: "yiyang_anhua_yuntai_mountain_tea_tourism_integration_area",
    name: "益阳安化云台山茶旅融合区",
    nameEn: "Yiyang Anhua Yuntai Mountain Tea-Tourism Integration Area",
    category: "modern",
    lat: 28.38,
    lng: 111.21,
    city: "益阳市安化县",
    description: "以安化黑茶和云台山风光为核心的茶旅综合体。",
    details: "该区域将万亩有机茶园与奇特的喀斯特地貌相结合，打造了集茶叶采摘制作、茶文化体验、山地运动和康养度假于一体的深度旅游目的地，是茶旅融合的杰出代表。",
    year: "2017",
    image: IMAGES.harvestFestival,
    tags: ["安化黑茶", "茶旅融合", "生态旅游"],
    significance: "探索茶产业转型升级",
  },
  {
    id: "loudi_xinhua_baixi_tofu_industrial_park",
    name: "娄底新化白溪豆腐产业园",
    nameEn: "Loudi Xinhua Baixi Tofu Industrial Park",
    category: "modern",
    lat: 27.74,
    lng: 111.3,
    city: "娄底市新化县",
    description: "以传统手工艺闻名的“豆腐之乡”产业基地。",
    details: "白溪豆腐以其独特的制作工艺和优良的水质而著称。产业园整合了当地的豆腐作坊，实行标准化生产和品牌化运营，使这一传统美食走向了更广阔的市场。",
    year: "2019",
    image: IMAGES.beautifulVillage,
    tags: ["白溪豆腐", "传统工艺", "产业升级"],
    significance: "传统手工艺的振兴",
  },
  {
    id: "chenzhou_yizhang_navel_orange_base",
    name: "郴州宜章脐橙基地",
    nameEn: "Chenzhou Yizhang Navel Orange Base",
    category: "modern",
    lat: 25.4,
    lng: 112.95,
    city: "郴州市宜章县",
    description: "湘南地区重要的优质脐橙出口基地。",
    details: "宜章县地处南岭山脉，气候适宜，是湖南优质脐橙的主产区之一。基地推行绿色种植标准，产品远销国内外市场，成为当地农业的支柱和农民增收的“黄金果”。",
    year: "1990s",
    image: IMAGES.dongtingHarvest,
    tags: ["脐橙", "出口农业", "绿色种植"],
    significance: "打造湘南水果名片",
  },
  {
    id: "yongzhou_daoxian_navel_orange_industrial_park",
    name: "永州道县脐橙产业园",
    nameEn: "Yongzhou Daoxian Navel Orange Industrial Park",
    category: "modern",
    lat: 25.53,
    lng: 111.59,
    city: "永州市道县",
    description: "集脐橙种植、加工、物流于一体的现代产业园。",
    details: "道县是“中国脐橙之乡”，产业园通过引进先进技术和设备，发展脐橙精深加工，开发果汁、果酱等高附加值产品，并配套冷链物流，构建了完整的现代农业产业链。",
    year: "2018",
    image: IMAGES.modernAgriculture,
    tags: ["道县脐橙", "全产业链", "精深加工"],
    significance: "构建现代水果产业链",
  },
  {
    id: "huaihua_huitong_konjac_base",
    name: "怀化会同魔芋基地",
    nameEn: "Huaihua Huitong Konjac Base",
    category: "modern",
    lat: 26.85,
    lng: 109.72,
    city: "怀化市会同县",
    description: "武陵山区重要的魔芋种植与加工基地。",
    details: "会同县利用其山地资源优势，大力发展魔芋产业。基地不仅进行规模化种植，还引进了加工企业，生产魔芋精粉、魔芋食品等，产品畅销海内外，有效带动了山区脱贫。",
    year: "2000s",
    image: IMAGES.anjiangRice,
    tags: ["魔芋", "山区农业", "健康食品"],
    significance: "山区特色产业助脱贫",
  },
  {
    id: "xiangxi_longshan_lily_industrial_park",
    name: "湘西龙山百合产业园",
    nameEn: "Xiangxi Longshan Lily Industrial Park",
    category: "modern",
    lat: 29.46,
    lng: 109.43,
    city: "湘西州龙山县",
    description: "“中国百合之乡”的核心产业园区。",
    details: "龙山县是全国最大的卷丹百合产区，龙山百合是国家地理标志产品。产业园集种球繁育、标准化种植、精深加工和市场交易于一体，是百合产业发展的龙头。",
    year: "2015",
    image: IMAGES.dongtingModern,
    tags: ["龙山百合", "地理标志", "食药同源"],
    significance: "引领全国百合产业",
  },
  {
    id: "changsha_ningxiang_pig_breeding_base",
    name: "长沙宁乡花猪养殖基地",
    nameEn: "Changsha Ningxiang Pig Breeding Base",
    category: "modern",
    lat: 28.26,
    lng: 112.55,
    city: "长沙市宁乡市",
    description: "中国四大名猪之一宁乡猪的保种与养殖基地。",
    details: "宁乡猪以其肉质细嫩、味道鲜美而闻名。基地采用“公司+农户”的模式，在保护地方优良品种的同时，进行规模化、标准化的生态养殖，推动了宁乡猪产业的复兴。",
    year: "2007",
    image: IMAGES.liuyangRice,
    tags: ["宁乡猪", "地方品种", "生态养殖"],
    significance: "保护地方优良种猪",
  },
  {
    id: "zhuzhou_youxian_xianggan_industrial_park",
    name: "株洲攸县香干产业园",
    nameEn: "Zhuzhou Youxian Spiced Dried Tofu Industrial Park",
    category: "modern",
    lat: 27.29,
    lng: 113.33,
    city: "株洲市攸县",
    description: "以攸县香干闻名的豆制品产业集聚区。",
    details: "攸县香干是湖南的传统名产。产业园通过统一标准、统一品牌、统一销售的模式，整合了众多香干生产企业，提升了产品质量和市场竞争力，成为县域经济的重要支柱。",
    year: "2014",
    image: IMAGES.nanxianShrimp,
    tags: ["攸县香干", "地方特产", "产业升级"],
    significance: "传统美食的产业化",
  },
  {
    id: "xiangtan_xiangxiang_shuifu_temple_fishery_base",
    name: "湘潭湘乡水府庙渔业基地",
    nameEn: "Xiangtan Xiangxiang Shuifu Temple Fishery Base",
    category: "modern",
    lat: 27.73,
    lng: 112.2,
    city: "湘潭市湘乡市",
    description: "依托水府庙水库发展的生态渔业示范基地。",
    details: "水府庙水库水质优良，是湖南重要的人工湖泊。渔业基地在此开展大水面生态养殖，注重水环境保护和渔业资源的可持续利用，出产的有机鱼深受消费者青睐。",
    year: "1990s",
    image: IMAGES.droneFarming,
    tags: ["生态渔业", "水库养殖", "有机鱼"],
    significance: "大水面生态渔业样板",
  },
  {
    id: "hengyang_nanyue_cloud_mist_tea_base",
    name: "衡阳南岳云雾茶基地",
    nameEn: "Hengyang Nanyue Cloud and Mist Tea Base",
    category: "modern",
    lat: 27.29,
    lng: 112.69,
    city: "衡阳市南岳区",
    description: "产自南岳衡山核心景区的高山云雾茶基地。",
    details: "南岳云雾茶自唐代即为贡品，生长于海拔800-1100米的山间。基地坚持有机种植和传统手工制作工艺，茶叶品质卓越，是宗教文化与茶文化结合的典范。",
    year: "1980s",
    image: IMAGES.teaGarden,
    tags: ["南岳云雾茶", "高山茶", "历史名茶"],
    significance: "传承千年贡茶文化",
  },
  {
    id: "shaoyang_xinning_langshan_navel_orange_base",
    name: "邵阳新宁崀山脐橙基地",
    nameEn: "Shaoyang Xinning Langshan Navel Orange Base",
    category: "modern",
    lat: 26.42,
    lng: 110.85,
    city: "邵阳市新宁县",
    description: "世界自然遗产地崀山脚下的优质脐橙产区。",
    details: "新宁县依托崀山独特的丹霞地貌和生态环境，发展脐橙产业。崀山脐橙果肉脆嫩、风味香甜，是国家地理标志保护产品，实现了生态保护与经济发展的双赢。",
    year: "1970s",
    image: IMAGES.harvestFestival,
    tags: ["崀山脐橙", "地理标志", "生态农业"],
    significance: "生态与产业融合发展",
  },
  {
    id: "yueyang_linxiang_float_industrial_park",
    name: "岳阳临湘浮标产业园",
    nameEn: "Yueyang Linxiang Float Industrial Park",
    category: "modern",
    lat: 29.48,
    lng: 113.45,
    city: "岳阳市临湘市",
    description: "全球最大的钓鱼浮标生产和出口基地。",
    details: "临湘浮标产业从家庭作坊起步，发展成为占据全球市场80%份额的特色产业。产业园集研发、生产、电商、物流于一体，是农村特色经济发展的奇迹。",
    year: "2013",
    image: IMAGES.beautifulVillage,
    tags: ["浮标", "特色产业", "电商经济"],
    significance: "小产品做成大产业",
  },
  {
    id: "changde_lixian_grape_industrial_park",
    name: "常德澧县葡萄产业园",
    nameEn: "Changde Lixian Grape Industrial Park",
    category: "modern",
    lat: 29.64,
    lng: 111.75,
    city: "常德市澧县",
    description: "澧阳平原上崛起的南方葡萄种植示范区。",
    details: "澧县利用其肥沃的土壤和充足的光照，引种改良葡萄品种，发展设施栽培。产业园推广标准化生产技术，打造区域品牌，成为南方葡萄产业的一颗新星。",
    year: "2010s",
    image: IMAGES.dongtingHarvest,
    tags: ["葡萄", "设施农业", "区域品牌"],
    significance: "南方葡萄种植新高地",
  },
  {
    id: "zhangjiajie_cili_eucommia_base",
    name: "张家界慈利杜仲基地",
    nameEn: "Zhangjiajie Cili Eucommia Base",
    category: "modern",
    lat: 29.43,
    lng: 111.13,
    city: "张家界市慈利县",
    description: "全国重要的杜仲种植和杜仲雄花茶产区。",
    details: "慈利县是“中国杜仲之乡”，拥有全国最大的杜仲林场。基地在传统药用种植基础上，成功开发出杜仲雄花茶等高附加值产品，开创了杜仲综合利用的新途径。",
    year: "1980s",
    image: IMAGES.modernAgriculture,
    tags: ["杜仲", "林下经济", "健康茶饮"],
    significance: "木本油料作物的创新",
  },
  {
    id: "yiyang_yuanjiang_asparagus_industrial_park",
    name: "益阳沅江芦笋产业园",
    nameEn: "Yiyang Yuanjiang Asparagus Industrial Park",
    category: "modern",
    lat: 28.84,
    lng: 112.35,
    city: "益阳市沅江市",
    description: "洞庭湖畔的“中国芦笋之乡”核心园区。",
    details: "沅江市利用洞庭湖冲积平原的沙质土壤，大规模种植芦笋，成为全国三大芦笋产区之一。产业园集芦笋罐头、芦笋饮料等加工于一体，产品远销欧美。",
    year: "1990s",
    image: IMAGES.anjiangRice,
    tags: ["芦笋", "出口创汇", "湖区农业"],
    significance: "湖区特色蔬菜产业",
  },
  {
    id: "pingjiang_uprising_exhibition",
    name: "平江起义旧址农运展馆",
    nameEn: "Pingjiang Uprising Memorial Hall - Peasant Movement Exhibition",
    category: "red",
    lat: 28.7,
    lng: 113.58,
    city: "岳阳市平江县",
    description: "纪念平江起义，展示土地革命时期农运历史。",
    details: "位于平江起义旧址内，系统展示了彭德怀领导的平江起义与湘鄂赣革命根据地农民运动的紧密联系。馆内陈列了大量农具、文件和照片，再现了‘打土豪、分田地’的土地革命场景，是研究中国共产党早期农运政策的重要窗口。",
    year: "1928",
    image: IMAGES.shaoshan,
    tags: ["平江起义", "农民运动", "土地革命"],
    significance: "湘鄂赣农运历史见证",
  },
  {
    id: "shazhou_half_quilt_story",
    name: "汝城沙洲村半条被子故事发生地",
    nameEn: "Rucheng Shazhou Village - 'Half a Quilt' Story Site",
    category: "red",
    lat: 25.55,
    lng: 113.69,
    city: "郴州市汝城县",
    description: "红军长征军民鱼水情的生动体现。",
    details: "该地是红军长征途中‘半条被子’故事的发生地。三位女红军借宿徐解秀老人家中，临走时将仅有的一条被子剪下一半留给老人。这个故事深刻诠释了共产党人与人民群众的血肉联系和鱼水深情，是红色基因和农耕文化交融的典范。",
    year: "1934",
    image: IMAGES.sangzhi,
    tags: ["长征故事", "军民鱼水情", "红色传承"],
    significance: "军民鱼水情的象征",
  },
  {
    id: "yanling_red_army_slogan_museum",
    name: "炎陵红军标语博物馆农事展区",
    nameEn: "Yanling Red Army Slogan Museum - Agricultural Exhibition Area",
    category: "red",
    lat: 26.49,
    lng: 113.77,
    city: "株洲市炎陵县",
    description: "通过红军标语，展现井冈山斗争时期的农事政策。",
    details: "博物馆收藏和展示了大量井冈山斗争时期留下的红军标语，其中农事展区专题陈列了‘实行土地革命’、‘废除苛捐杂税’等内容的标语。这些标语是当时共产党农民主张的直接物证，反映了革命战争与农业生产的互动关系。",
    year: "1928",
    image: IMAGES.redHeritage,
    tags: ["红军标语", "井冈山斗争", "农业政策"],
    significance: "革命时期农事宣传",
  },
  {
    id: "chaling_worker_peasant_government",
    name: "茶陵工农兵政府旧址",
    nameEn: "Chaling Workers-Peasants-Soldiers Government Former Site",
    category: "red",
    lat: 26.79,
    lng: 113.55,
    city: "株洲市茶陵县",
    description: "中国第一个县级工农兵政府，土地革命的先行者。",
    details: "1927年，毛泽东率秋收起义部队攻占茶陵，建立了中国历史上第一个县级工农兵政权。该旧址见证了共产党早期在县域层面推行‘耕者有其田’政策的伟大尝试，对探索农村革命道路具有开创性意义，是农运史上的重要里程碑。",
    year: "1927",
    image: IMAGES.shaoshan,
    tags: ["工农兵政府", "秋收起义", "耕者有其田"],
    significance: "首个县级红色政权",
  },
  {
    id: "southern_hunan_uprising_hq",
    name: "湘南暴动指挥部旧址农运展区",
    nameEn: "Southern Hunan Uprising HQ Former Site - Peasant Movement Exhibition",
    category: "red",
    lat: 25.76,
    lng: 112.59,
    city: "郴州市宜章县",
    description: "展示朱德、陈毅领导湘南暴动中的农民运动。",
    details: "旧址是1928年朱德、陈毅领导湘南暴动的指挥中心。其农运展区通过实物和图文资料，集中展示了暴动期间组织农民协会、分配土地、建立红色政权的史实。它体现了武装斗争与农民运动相结合的革命策略，在湖南农运史上地位显赫。",
    year: "1928",
    image: IMAGES.sangzhi,
    tags: ["湘南暴动", "朱德陈毅", "农民协会"],
    significance: "武装斗争与农运结合",
  },
  {
    id: "liling_xiannongtan_relic",
    name: "醴陵先农坛革命遗址",
    nameEn: "Liling Altar of Agriculture Revolutionary Site",
    category: "red",
    lat: 27.66,
    lng: 113.5,
    city: "株洲市醴陵市",
    description: "左权曾在此领导农民运动，是醴陵农运的中心。",
    details: "先农坛原是祭祀先农之所，大革命时期成为醴陵农民运动的策源地。1926年至1927年，左权等共产党人在此成立农民协会，组织农民自卫军，开展减租减息斗争。这里是醴陵红色农运的摇篮，见证了农民力量的觉醒与组织过程。",
    year: "1926",
    image: IMAGES.redHeritage,
    tags: ["左权", "农民协会", "减租减息"],
    significance: "县域农运策源地",
  },
];

export const THEME_ROUTES = [
  {
    id: "origin",
    name: "农耕文明探源",
    nameEn: "Origins of Farming Civilization",
    color: "#8B6914",
    category: "ancient" as SiteCategory,
    description: "追溯万年稻源，探寻湖湘农耕文明的根脉",
    sites: ["yuchanyan", "pengtoushan", "chengtoushan", "gaomiao", "ziquejie", "liye", "mawangdui", "datang_site", "bashidang_site", "tonggushan_site", "tanheli_site", "laosicheng_site", "yuelu_academy_agricultural_museum", "linli_kemu_mountain_site", "shimen_zaoshi_site"],
    image: IMAGES.ancientFarming,
  },
  {
    id: "digital",
    name: "数字农旅体验",
    nameEn: "Digital Agri-Tourism",
    color: "#1B7A4E",
    category: "modern" as SiteCategory,
    description: "感受科技农业的脉动，体验智慧田园的魅力",
    sites: ["anjiang", "longping_museum", "nanxian_shrimp", "liuyang_rice", "dongting_modern", "tea_culture", "drone_base", "harvest_fest", "beautiful_village", "changde_liuyehu_modern_agriculture_park", "yueyang_junshan_silver_needle_tea_garden", "xiangxi_kiwi_fruit_industrial_park", "huaihua_bingtang_orange_base", "zhuzhou_yanling_yellow_peach_base"],
    image: IMAGES.modernAgriculture,
  },
  {
    id: "red",
    name: "红色农事教育",
    nameEn: "Red Agricultural Heritage",
    color: "#C0392B",
    category: "red" as SiteCategory,
    description: "重温革命岁月，传承红色农魂的不朽精神",
    sites: ["shaoshan", "sangzhi_granary", "huaminglou", "qiusc", "tongdao", "pingjiang_uprising_exhibition", "shazhou_half_quilt_story", "yanling_red_army_slogan_museum", "chaling_worker_peasant_government", "southern_hunan_uprising_hq", "liling_xiannongtan_relic"],
    image: IMAGES.redHeritage,
  },
];

export const STATS = {
  totalSites: 109,
  ancientSites: 43,
  modernSites: 55,
  redSites: 11,
  historyYears: "14000+",
  provinces: "14个市州",
  heritage: "3项世界遗产",
};
